inputdirs: 
  - /fast/users/szyskam_c/work/testdata/dockersnake
workdir: /fast/users/szyskam_c/scratch/develop/Dockersnake # here your results are created
snakedir: /fast/users/szyskam_c/snakes/develop/dockersnake
envs: env # the folder of the env-files (MacOS requires different environments)
samples: # here go all your samples
  samplesheet: /fast/users/szyskam_c/snakes/develop/dockersnake/configs/sheets/test.csv
  tumor:
    - A  #
  normal:
    - B  # if more than one, the first normal will be used as default for tumor-sample
#### ABSOLUTE PATHS ############
paths:
  mystatic: /fast/groups/ag_damm/work/ref/
  scripts: scripts/ # folder relative to snakedir
#### REF SECTION ###############
ref:
  build: hg38
  hg38:
    genome_path: genome/gatk/hg38/
    genome: genome/gatk/hg38/hg38.fasta
    genome_split: genome/gatk/hg38/split
    dbsnp: annotation/gatk/hg38/dbsnp_138.hg38.vcf
    dbsnp_all: annotation/gatk/hg38/All_20180418.vcf
    dbsnp_common: annotation/gatk/hg38/common_all_20180418.vcf
    gold_standard_indels: annotation/gatk/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf
    phase1k_indels: annotation/gatk/hg38/1000G_phase1.snps.high_confidence.hg38.vcf # seems to work instead of indels (acc. to GATK blog: https://gatkforums.broadinstitute.org/gatk/discussion/6800/known-sites-for-indel-realignment-and-bqsr-in-hg38-bundle)
    # bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
    # bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
scripts:
  # fastq
  split_fastq: shell/split_fastq.mawk
  # BEDcoverage
  prettifyBED : shell/prettify_BEDcoverage.awk
  # varscan2anno
  vcf2csv: shell/vcf2csv.mawk
  editcsv: shell/editcsvVarscan.mawk
  coords2annovar: shell/coords2annovar.mawk
  varscan2table: shell/varscan2table.mawk
  # annovar
  anno_info: shell/anno_info.mawk
  # EBfilter
  cleanpileup: shell/cleanpileup.mawk
  pile2count: shell/pile2count.mawk
  matrix2EBinput: shell/matrix2EBinput.mawk
  makeponlist: shell/makeponlist.sh
  csv2bed: shell/csv2bed.mawk
  pon2cols: shell/pon2cols.mawk
  reducematrix: shell/matrix_minus_sample.mawk
  reordermatrix: shell/reorder_matrix.mawk
resplit_bam:
  threads: 8
EBFilter:
  run: True
  pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
  use_cache: True
  cache_folder: PoN/HAEv7_hg38_NovaSeq # path relative to mystatic path
  full_pon_output: False
  threads:
    pileup: 12
    makeEBcache: 20
    EBscore: 20
    EBsplit_factor: 20 # into how many jobs is makeEBcache divided per chromosome
  params:
    sep: tab
    MAPQ: 20   # I guess this should be lower than the mapping quality used for mpileup or not?
    Q: 25
    fitting_penalty: 0.5